#!/bin/bash

set -e

if [ ! -f /assets/aerobase_2.17.0-1_amd64.deb ]; then
  curl -L "https://dl.bintray.com/aerobase/aerobase-deb/aerobase_2.17.0-1_amd64.deb" -o /tmp/aerobase_2.17.0-1_xenial.deb
else
  cp /assets/aerobase_2.17.0-1_xenial.deb /tmp  
fi

if [ ! -f /assets/aerobase-iam_2.17.0-1_xenial.deb ]; then
  curl -L "https://dl.bintray.com/aerobase/aerobase-deb/aerobase-iam_2.17.0-1_amd64.deb" -o /tmp/aerobase-iam_2.17.0-1_amd64.deb
else
  cp /assets/aerobase-iam_2.17.0-1_xenial.deb /tmp
fi
