#!/bin/bash

set -e

if [ ! -f /assets/aerobase_23.0.7-4_amd64.deb ]; then
  curl -L -k "https://packages.aerobase.io/deb/aerobase_23.0.7-4_amd64.deb" -o /tmp/aerobase_23.0.7-4_amd64.deb
else
  cp /assets/aerobase_23.0.7-4_amd64.deb /tmp  
fi

if [ ! -f /assets/aerobase-iam_23.0.7-4_amd64.deb ]; then
  curl -L -k "https://packages.aerobase.io/deb/aerobase-iam_23.0.7-4_amd64.deb" -o /tmp/aerobase-iam_23.0.7-4_amd64.deb
else
  cp /assets/aerobase-iam_23.0.7-4_amd64.deb /tmp
fi


